### ISSUE TITLE
Broken patches

### ISSUE THREAD

**Issue by bdejong** [pingdynasty/OwlPatches#28]
Hey guys,

https://github.com/pingdynasty/OwlPatches/blob/master/TestTonePatch.hpp

```
float* samples = buffer.getSamples(0);
// ...
for(int n = 0; n<size; n++){
      left[n] = sinf(2*M_PI*pos) * amplitude;
// ...
```

it's kind of nasty if your most basic examples don't compile..

**Comment by pingdynasty** [comment]
Thanks - fixed now. The codebase is constantly evolving so some of the examples have fallen off the radar.

The best place to go for example patches is the online patch library:
https://hoxtonowl.com/patch-library/patches/latest

If you come across any more issues let us know!

**Comment by bdejong** [comment]
👍

**Comment by bdejong** [comment]
( by the way, the compiler tells me StompBox is deprecated... I see it's still included in many of the patches... )
